using { /Fortnite.com/Devices }
using { /Verse.org/Simulation }
using { /Verse.org/Simulation/Tags }

# Derive from the `tag` class in the Verse.org/Simulation/Tags module to create a new gameplay tag.
snowButton := class(tag){}
snowVFX := class(tag){}
snowPile := class(tag){}
Gold := class(tag){}
Silver := class(tag){}
Bronze := class(tag){}
Vend := class(tag){}
SnowLaunchVendTimer := class(tag){}
Waypoint := class(tag){}
